server:
  port: 8888
 
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wesleyav/curso-alura-microservices-com-spring-cloud-registry-config-server-e-distributed-tracing/blob/main/microservice-repo/
          search-paths: fornecedor